# Generated by Django 5.2 on 2025-05-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='subject',
        ),
        migrations.AddField(
            model_name='ticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='support_attachments/'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
