# Generated by Django 5.2 on 2025-05-24 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_remove_ticket_subject_ticket_attachment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='General Support', max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='email',
            field=models.EmailField(default='default@example.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='full_name',
            field=models.CharField(default='Anonymous', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TicketReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='support_replies/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.ticket')),
            ],
        ),
    ]
