# Generated by Django 4.2.21 on 2025-05-25 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('postcode', models.CharField(max_length=10)),
                ('bio', models.TextField(blank=True, null=True)),
                ('skills', models.TextField(blank=True, null=True)),
                ('certifications', models.CharField(blank=True, default='', max_length=255)),
                ('average_rating', models.CharField(blank=True, default='none', max_length=100, null=True)),
                ('role', models.CharField(choices=[('get', 'Get things done'), ('earn', 'Earn money')], default='get', max_length=10)),
                ('account_type', models.CharField(choices=[('individual', 'Individual'), ('business', 'Business User')], default='individual', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
