# Generated by Django 5.2.1 on 2025-05-24 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_average_rating_profile_bio_profile_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='certifications',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
