# Generated by Django 5.2.1 on 2025-05-24 13:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_category_alter_offer_amount_alter_offer_message_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_tasks', to=settings.AUTH_USER_MODEL),
        ),
    ]
